databases:
  - name: postgres
    databaseName: join_production
    user: join
    plan: free

services:
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lfu
  - type: web
    name: join_production
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL # this must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: redis
          property: connectionString
      